spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama2


#    openai:
#      api-key: "YOUR_OPENAI_API_KEY"
#      chat:
#        options:
#          model: gpt-4o-mini
