spring:
  ai:
    ollama:
      base-url: http://localhost:11434
#      init:
#        pull-model-strategy: when_missing
      chat:
        options:
          model: llama2
          temperature: 0.7


#    openai:
#      api-key: ${OPENAI_API_KEY}
#      chat:
#        model: gpt-3.5-turbo
#        temperature: 0.7
